### Array operations

In [2]:
import numpy as np

In [3]:
num = np.array([56,43,12,67,61,48])

In [4]:
print(num)

[56 43 12 67 61 48]


In [5]:
num

array([56, 43, 12, 67, 61, 48])

In [6]:
type(num)

numpy.ndarray

In [8]:
num.dtype

dtype('int64')

In [9]:
num.size

6

In [11]:
num.ndim

1

In [12]:
x = np.array([45,23,34.56,12,56])

In [13]:
x

array([45.  , 23.  , 34.56, 12.  , 56.  ])

In [14]:
x.dtype

dtype('float64')

In [15]:
x[0]

45.0

In [17]:
y = np.array([[5,6,7],[2,1,8]])

In [18]:
y

array([[5, 6, 7],
       [2, 1, 8]])

In [19]:
y.ndim

2

In [20]:
y.size

6

In [23]:
y[0][2]

7

In [24]:
y = np.array([[5,6,7],[2,1,8],
             [3,2,1],[6,9,0]])

In [25]:
y

array([[5, 6, 7],
       [2, 1, 8],
       [3, 2, 1],
       [6, 9, 0]])

In [26]:
y.shape

(4, 3)

In [27]:
y.reshape(3,4)

array([[5, 6, 7, 2],
       [1, 8, 3, 2],
       [1, 6, 9, 0]])

In [28]:
y.reshape(-1,2)

array([[5, 6],
       [7, 2],
       [1, 8],
       [3, 2],
       [1, 6],
       [9, 0]])

In [29]:
y.reshape(3,-1)

array([[5, 6, 7, 2],
       [1, 8, 3, 2],
       [1, 6, 9, 0]])

In [30]:
y.flatten()

array([5, 6, 7, 2, 1, 8, 3, 2, 1, 6, 9, 0])

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [33]:
np.arange(2,10,0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. , 9.5])

In [34]:
np.arange(10,4,-0.5)

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5])

In [35]:
x = [4,5,6,7]
y = np.array([4,5,6,7])

In [36]:
x * 2

[4, 5, 6, 7, 4, 5, 6, 7]

In [37]:
y * 2

array([ 8, 10, 12, 14])

In [38]:
y / 3

array([1.33333333, 1.66666667, 2.        , 2.33333333])

In [39]:
y - 2

array([2, 3, 4, 5])

In [40]:
y.max()

7

In [41]:
y.mean()

5.5

In [42]:
y.std()

1.118033988749895

In [44]:
x = [45,33,12,56,43,66,32,23]

In [45]:
np.argmax(x)

5

In [46]:
np.sort(x)

array([12, 23, 32, 33, 43, 45, 56, 66])

In [47]:
np.sqrt(x)

array([6.70820393, 5.74456265, 3.46410162, 7.48331477, 6.55743852,
       8.1240384 , 5.65685425, 4.79583152])

In [48]:
x = np.array([5,4,2,3])
y = np.array([9,8,1,3])

In [49]:
x + y

array([14, 12,  3,  6])

In [50]:
x * y

array([45, 32,  2,  9])

In [52]:
x.

TypeError: only integer scalar arrays can be converted to a scalar index

### Series object

In [54]:
import pandas as pd

In [55]:
s = pd.Series([67,33,12,56,78,21])

In [56]:
s

0    67
1    33
2    12
3    56
4    78
5    21
dtype: int64

In [57]:
s[3]

56

In [58]:
s[3] = 12
s

0    67
1    33
2    12
3    12
4    78
5    21
dtype: int64

In [59]:
s.dtype

dtype('int64')

In [60]:
type(s)

pandas.core.series.Series

In [62]:
s = pd.Series([67,33,12,56,78,21],
             index=range(100,106))

In [63]:
s

100    67
101    33
102    12
103    56
104    78
105    21
dtype: int64

In [64]:
s[102]

12

### DataFrame

In [67]:
roll = pd.Series(range(1,6))
name = pd.Series(['Akash','Ajay','Asha',
                 'Amruta','Anil'])
marks = pd.Series([56.78, 65.23, 76.34, 61.23,
                  71.34])

In [69]:
df = pd.DataFrame({
    'Roll': roll,
    'Name': name,
    'Marks': marks
})

In [70]:
df

Roll    Name  Marks
0     1   Akash  56.78
1     2    Ajay  65.23
2     3    Asha  76.34
3     4  Amruta  61.23
4     5    Anil  71.34

In [71]:
type(df)

pandas.core.frame.DataFrame

In [72]:
df.shape

(5, 3)

In [73]:
df.dtypes

Roll       int64
Name      object
Marks    float64
dtype: object

### Structured Data Analysis

In [75]:
import os
os.getcwd()

'/home/mitu'

In [77]:
# Location: https://mitu.co.in/dataset
# Download all student* files

In [78]:
df = pd.read_csv('student.csv')

In [79]:
df

roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [82]:
cols = ['A','B','C','D','H']
df = pd.read_csv('student1.csv', names=cols)

In [83]:
df

A        B   C      D   H
0   1     anil  TE  56.77  22
1   2     amit  TE  59.77  21
2   3   aniket  BE  76.88  19
3   4  ajinkya  TE  69.66  20
4   5     asha  TE  63.28  20
5   6   ayesha  BE  49.55  20
6   7     amar  BE  65.34  19
7   8    amita  BE  68.33  23
8   9     amol  TE  56.75  20
9  10    anmol  BE  78.66  21

In [86]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',
                names = ['SL','SW','PL','PW','SP'])

In [87]:
df

SL   SW   PL   PW              SP
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [90]:
df = pd.read_csv('student3.tsv', sep='\t')

In [91]:
df

roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [95]:
df=pd.read_csv('student.csv')

In [96]:
df.shape

(10, 5)

In [97]:
df.ndim

2

In [98]:
df.size

50

In [99]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [100]:
df.T

0      1       2        3      4       5      6      7      8  \
roll       1      2       3        4      5       6      7      8      9   
name    anil   amit  aniket  ajinkya   asha  ayesha   amar  amita   amol   
class     TE     TE      BE       TE     TE      BE     BE     BE     TE   
marks  56.77  59.77   76.88    69.66  63.28   49.55  65.34  68.33  56.75   
age       22     21      19       20     20      20     19     23     20   

           9  
roll      10  
name   anmol  
class     BE  
marks  78.66  
age       21

In [101]:
df.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20],
       [6, 'ayesha', 'BE', 49.55, 20],
       [7, 'amar', 'BE', 65.34, 19],
       [8, 'amita', 'BE', 68.33, 23],
       [9, 'amol', 'TE', 56.75, 20],
       [10, 'anmol', 'BE', 78.66, 21]], dtype=object)

In [102]:
df.min()

roll           1
name     ajinkya
class         BE
marks      49.55
age           19
dtype: object

In [103]:
df.max()

roll         10
name     ayesha
class        TE
marks     78.66
age          23
dtype: object

In [104]:
df.sum()

roll                                                    55
name     anilamitaniketajinkyaashaayeshaamaramitaamolanmol
class                                 TETEBETETEBEBEBETEBE
marks                                               644.99
age                                                    205
dtype: object

In [105]:
df.mean()

roll      5.500
marks    64.499
age      20.500
dtype: float64

In [106]:
df.median()

roll      5.50
marks    64.31
age      20.00
dtype: float64

In [109]:
x = np.array([23,56,11,24,75,39,43,67])

In [110]:
np.median(x)

41.0

In [112]:
x.sort()
x

array([11, 23, 24, 39, 43, 56, 67, 75])

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   roll    10 non-null     int64  
 1   name    10 non-null     object 
 2   class   10 non-null     object 
 3   marks   10 non-null     float64
 4   age     10 non-null     int64  
dtypes: float64(1), int64(2), object(2)
memory usage: 528.0+ bytes


In [114]:
df.describe()

roll      marks        age
count  10.00000  10.000000  10.000000
mean    5.50000  64.499000  20.500000
std     3.02765   9.207179   1.269296
min     1.00000  49.550000  19.000000
25%     3.25000  57.520000  20.000000
50%     5.50000  64.310000  20.000000
75%     7.75000  69.327500  21.000000
max    10.00000  78.660000  23.000000

In [115]:
df.mode()

roll     name class  marks   age
0     1  ajinkya    BE  49.55  20.0
1     2     amar    TE  56.75   NaN
2     3     amit   NaN  56.77   NaN
3     4    amita   NaN  59.77   NaN
4     5     amol   NaN  63.28   NaN
5     6   aniket   NaN  65.34   NaN
6     7     anil   NaN  68.33   NaN
7     8    anmol   NaN  69.66   NaN
8     9     asha   NaN  76.88   NaN
9    10   ayesha   NaN  78.66   NaN

#### Slicing using iloc

In [117]:
x = df.iloc[4:8, 1:4]

In [118]:
x

name class  marks
4    asha    TE  63.28
5  ayesha    BE  49.55
6    amar    BE  65.34
7   amita    BE  68.33

In [119]:
df.iloc[4:, 1:4]

name class  marks
4    asha    TE  63.28
5  ayesha    BE  49.55
6    amar    BE  65.34
7   amita    BE  68.33
8    amol    TE  56.75
9   anmol    BE  78.66

In [120]:
df.iloc[:8, 1:4]

name class  marks
0     anil    TE  56.77
1     amit    TE  59.77
2   aniket    BE  76.88
3  ajinkya    TE  69.66
4     asha    TE  63.28
5   ayesha    BE  49.55
6     amar    BE  65.34
7    amita    BE  68.33

In [121]:
df.iloc[:, 1:4]

name class  marks
0     anil    TE  56.77
1     amit    TE  59.77
2   aniket    BE  76.88
3  ajinkya    TE  69.66
4     asha    TE  63.28
5   ayesha    BE  49.55
6     amar    BE  65.34
7    amita    BE  68.33
8     amol    TE  56.75
9    anmol    BE  78.66

In [123]:
df.iloc[4:, 1:]

name class  marks  age
4    asha    TE  63.28   20
5  ayesha    BE  49.55   20
6    amar    BE  65.34   19
7   amita    BE  68.33   23
8    amol    TE  56.75   20
9   anmol    BE  78.66   21

In [124]:
df.iloc[:, :]

roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [125]:
df.iloc[[4,6,7,2],:]

roll    name class  marks  age
4     5    asha    TE  63.28   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
2     3  aniket    BE  76.88   19

In [126]:
df.iloc[[4,6,7,2],[1,3,4]]

name  marks  age
4    asha  63.28   20
6    amar  65.34   19
7   amita  68.33   23
2  aniket  76.88   19

In [127]:
df.iloc[4,:]

roll         5
name      asha
class       TE
marks    63.28
age         20
Name: 4, dtype: object

In [128]:
df.iloc[[4],:]

roll  name class  marks  age
4     5  asha    TE  63.28   20

In [130]:
df.iloc[:,3]

0    56.77
1    59.77
2    76.88
3    69.66
4    63.28
5    49.55
6    65.34
7    68.33
8    56.75
9    78.66
Name: marks, dtype: float64

#### Slicing with loc

In [133]:
df.loc[:,'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [134]:
df.loc[:,['name','marks']]

name  marks
0     anil  56.77
1     amit  59.77
2   aniket  76.88
3  ajinkya  69.66
4     asha  63.28
5   ayesha  49.55
6     amar  65.34
7    amita  68.33
8     amol  56.75
9    anmol  78.66

In [135]:
df['name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [136]:
df[['name','marks']]

name  marks
0     anil  56.77
1     amit  59.77
2   aniket  76.88
3  ajinkya  69.66
4     asha  63.28
5   ayesha  49.55
6     amar  65.34
7    amita  68.33
8     amol  56.75
9    anmol  78.66

In [137]:
df.name

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [138]:
df.drop(5)

roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [139]:
df.drop([5,8,9])

roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23

In [140]:
df.drop('class', axis = 1)

roll     name  marks  age
0     1     anil  56.77   22
1     2     amit  59.77   21
2     3   aniket  76.88   19
3     4  ajinkya  69.66   20
4     5     asha  63.28   20
5     6   ayesha  49.55   20
6     7     amar  65.34   19
7     8    amita  68.33   23
8     9     amol  56.75   20
9    10    anmol  78.66   21

In [142]:
df.drop(['class','age'], axis = 1)

roll     name  marks
0     1     anil  56.77
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28
5     6   ayesha  49.55
6     7     amar  65.34
7     8    amita  68.33
8     9     amol  56.75
9    10    anmol  78.66

In [143]:
df.sum()

roll                                                    55
name     anilamitaniketajinkyaashaayeshaamaramitaamolanmol
class                                 TETEBETETEBEBEBETEBE
marks                                               644.99
age                                                    205
dtype: object

In [144]:
df.sum(axis=1)

0     79.77
1     82.77
2     98.88
3     93.66
4     88.28
5     75.55
6     91.34
7     99.33
8     85.75
9    109.66
dtype: float64

In [145]:
df['marks'].mean()

64.499

In [146]:
df['marks'].max()

78.66

In [147]:
df['marks'].min()

49.55

In [148]:
df['marks'].sum()

644.9899999999999

In [149]:
df['marks'].std()

9.207178901994535

In [151]:
type(df['marks'])

pandas.core.series.Series

In [152]:
df['marks'].values

array([56.77, 59.77, 76.88, 69.66, 63.28, 49.55, 65.34, 68.33, 56.75,
       78.66])

In [157]:
x = [5,6,7]
y = x.copy()

In [158]:
x.append(8)

In [159]:
x

[5, 6, 7, 8]

In [160]:
y

[5, 6, 7]

In [161]:
newdf = df.copy()

In [162]:
id(df)

140081316663888

In [163]:
id(x)

140081331883072

In [164]:
newdf = df
id(newdf)

140081316663888

In [165]:
newdf = df.copy()
id(newdf)

140081315080944

#### Adding a new column

In [167]:
gender = np.array(['M','M','M','M','F',
                   'F','M','F','M','M'])

In [168]:
gender

array(['M', 'M', 'M', 'M', 'F', 'F', 'M', 'F', 'M', 'M'], dtype='<U1')

In [169]:
df['gender'] = gender

In [170]:
df

roll     name class  marks  age gender
0     1     anil    TE  56.77   22      M
1     2     amit    TE  59.77   21      M
2     3   aniket    BE  76.88   19      M
3     4  ajinkya    TE  69.66   20      M
4     5     asha    TE  63.28   20      F
5     6   ayesha    BE  49.55   20      F
6     7     amar    BE  65.34   19      M
7     8    amita    BE  68.33   23      F
8     9     amol    TE  56.75   20      M
9    10    anmol    BE  78.66   21      M

In [171]:
df['cgpa'] = df['marks'] / 10 + 1.05

In [172]:
df

roll     name class  marks  age gender   cgpa
0     1     anil    TE  56.77   22      M  6.727
1     2     amit    TE  59.77   21      M  7.027
2     3   aniket    BE  76.88   19      M  8.738
3     4  ajinkya    TE  69.66   20      M  8.016
4     5     asha    TE  63.28   20      F  7.378
5     6   ayesha    BE  49.55   20      F  6.005
6     7     amar    BE  65.34   19      M  7.584
7     8    amita    BE  68.33   23      F  7.883
8     9     amol    TE  56.75   20      M  6.725
9    10    anmol    BE  78.66   21      M  8.916